# Workflow Name
name: Hello

# Trigger the workflow manually from the GitHub Actions tab
on:
  workflow_dispatch:

# Jobs to be executed
jobs:
  # First job
  say-hello:
    # Runner environment
    runs-on: ubuntu-latest

    # Steps to execute
    steps:
      # Print a message
      - name: Say hello to everyone
        run: echo "Hello DOSTO"
