name: Autolinter

on:
  push:
    paths:
      - "**/*.py"

jobs:
  code:
    runs-on: ubuntu-latest

    steps:
      # Clone the repository
      - name: Checkout the code
        uses: actions/checkout@v4

      # Install Ruff
      - name: Install linter
        run: pip install ruff

      # Run Ruff
      - name: Check Python files using Ruff
        run: ruff check .
